server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dorm_system?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT-8
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mywork.dorm.Bean
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#showSql
logging:
  level:
    com:
      example:
        mapper : debug